server:
  port: 8800

spring:
  application:
    name: product-stock-service
  datasource:
    url: jdbc:postgresql://localhost:5433/my_db
    username: postgres
    password: password1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

my-values:
  name: DEV
  description: Some INFO
